// <auto-generated />
using System;
using BuckeyeMarketplaceApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuckeyeMarketplaceApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("BuckeyeMarketplaceApi.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("BuckeyeMarketplaceApi.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CartId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("BuckeyeMarketplaceApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("SellerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Textbooks",
                            Description = "8th edition, lightly used. Some highlighting in chapters 1-5. Great condition overall.",
                            ImageUrl = "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=400&h=300&fit=crop",
                            PostedDate = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 45.00m,
                            SellerName = "Marcus J.",
                            Title = "Intro to Calculus Textbook"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electronics",
                            Description = "Works perfectly, includes charging cable. Used for two semesters of math courses.",
                            ImageUrl = "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=400&h=300&fit=crop",
                            PostedDate = new DateTime(2026, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 75.00m,
                            SellerName = "Aisha R.",
                            Title = "TI-84 Plus CE Graphing Calculator"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Furniture",
                            Description = "Adjustable LED desk lamp, white. Barely used, moving out of dorm.",
                            ImageUrl = "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=400&h=300&fit=crop",
                            PostedDate = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 15.00m,
                            SellerName = "Jake T.",
                            Title = "IKEA Desk Lamp"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Clothing",
                            Description = "Official OSU merch, scarlet red, size Large. Worn a handful of times.",
                            ImageUrl = "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=400&h=300&fit=crop",
                            PostedDate = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 25.00m,
                            SellerName = "Taylor M.",
                            Title = "OSU Crewneck Sweatshirt (Large)"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Textbooks",
                            Description = "6th edition. No writing or highlighting inside. Includes access code (unused).",
                            ImageUrl = "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400&h=300&fit=crop",
                            PostedDate = new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 55.00m,
                            SellerName = "Priya K.",
                            Title = "Introduction to Psychology Textbook"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Electronics",
                            Description = "Selling because I switched to over-ear headphones. Comes with original case and tips.",
                            ImageUrl = "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=400&h=300&fit=crop",
                            PostedDate = new DateTime(2026, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 120.00m,
                            SellerName = "Marcus J.",
                            Title = "Apple AirPods Pro (2nd Gen)"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Furniture",
                            Description = "3.2 cu ft compact fridge, black. Perfect for dorm rooms. Pick up only.",
                            ImageUrl = "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=400&h=300&fit=crop",
                            PostedDate = new DateTime(2026, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 60.00m,
                            SellerName = "Chris L.",
                            Title = "Mini Fridge (Dorm Size)"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Clothing",
                            Description = "Nike Pegasus 40, barely worn. Bought wrong size online, only used twice.",
                            ImageUrl = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=300&fit=crop",
                            PostedDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 65.00m,
                            SellerName = "Aisha R.",
                            Title = "Nike Running Shoes (Size 10)"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Textbooks",
                            Description = "Covers all major topics in organic chemistry. All pages intact, used for one semester.",
                            ImageUrl = "https://images.unsplash.com/photo-1532634993-15f421e42ec0?w=400&h=300&fit=crop",
                            PostedDate = new DateTime(2026, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 20.00m,
                            SellerName = "Jake T.",
                            Title = "Intro to Organic Chemistry Textbook"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Electronics",
                            Description = "Logitech M720 Triathlon. Multi-device Bluetooth mouse, great for studying.",
                            ImageUrl = "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&h=300&fit=crop",
                            PostedDate = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 30.00m,
                            SellerName = "Taylor M.",
                            Title = "Logitech Wireless Mouse"
                        });
                });

            modelBuilder.Entity("BuckeyeMarketplaceApi.Models.CartItem", b =>
                {
                    b.HasOne("BuckeyeMarketplaceApi.Models.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuckeyeMarketplaceApi.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BuckeyeMarketplaceApi.Models.Cart", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
